Also, more tomdoc dockblocks.

diff --git a/functions/funcEnd b/functions/funcEnd
--- a/functions/funcEnd
+++ b/functions/funcEnd
@@ -1,22 +1,36 @@
 #! /bin/bash
 
-#-> 
-#-> 
-#-> 
-function funcEnd() {
+# The version of the function file in format "x.y.z".
+export JLB_FUNCEND_VERSION=1.0.0
+
+# Public: Indicates where a function begins
+#
+# When debugging, states in terminal output where a function ends,
+# as well as the provided return value. Also decrements JLB_DEBUG_DEPTH
+# for use by jlb::debug
+#
+# $1 - OPTIONAL: the return value to be included in the output.
+#
+# Examples
+#
+#   jlb::funcEnd
+#   jlb::funcEnd "${errcode}"
+#
+# Returns the result of jlb::debug
+function jlb::funcEnd() {
 	local errcode
 	local retval="${*}"
 	local str="END FUNCTION ${FUNCNAME[1]}"
 
 	if [ ! -z "${retval}" ] ; then
-		str="${str} with errcode of $retval"
+		str="${str} with return value of $retval"
 	fi
 
-	((DEBUG_DEPTH--))
+	((JLB_DEBUG_DEPTH--))
+	export JLB_DEBUG_DEPTH
 
-	debug "${str}" ; errcode=$?
-	return $errcode
+	jlb::debug "${str}" ; errcode=$?
+	return ${errcode}
 }
 
-debug "Sourced file: ${BASH_SOURCE[0]}"
-debug
+jlb::debug "Sourced file: ${BASH_SOURCE[0]}"
diff --git a/functions/init b/functions/init
--- a/functions/init
+++ b/functions/init
@@ -1,23 +1,70 @@
 #! /bin/bash
 
-#-> PRIMARY INITIALISATION SYSTEM FOR ALL SCRIPTS
+# The version of the function file in format "x.y.z".
+export JLB_INIT_VERSION=1.0.0
 
-# Root directory containing this repos' file structure
-_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+# Public: Primary initialisation system for library
+#
+# Sources core functions and runs the loader.
+#
+# $1 - Path the directory containing this init file.
+# $2 - OPTIONAL: 
+#
+# Examples
+#
+#   init "${jlb_root}"
+#
+# Returns 0 unless jlb::loader fails.
+function jlb::init() {
+	local	errcode \
+			path
 
-#-> SOURCE CORE FUNCTION FILES
-# shellcheck source=./debug
-source "${_ROOT}/debug"
-# shellcheck source=./funcStart
-source "${_ROOT}/funcStart"
-# shellcheck source=./funcEnd
-source "${_ROOT}/funcEnd"
-# shellcheck source=./errcho
-source "${_ROOT}/errcho"
-# shellcheck source=./loader
-source "${_ROOT}/loader"
+	path="${*}"
+	#-> SOURCE CORE FUNCTION FILES
+	# shellcheck source=./debug
+	source "${path}/debug"
+	# shellcheck source=./funcStart
+	source "${path}/funcStart"
+	# shellcheck source=./funcEnd
+	source "${path}/funcEnd"
+	# shellcheck source=./printerr
+	source "${path}/printerr"
+	# shellcheck source=./loader
+	source "${path}/loader"
 
-#-> CALL THE LOADER ON THE PROJECT ROOT
-loader "${_ROOT}" "0" "*.sh"
+	#-> CALL THE LOADER ON THE PROJECT ROOT
+	if ! jlb::loader "${path}" "0" "*.sh" ; then
+		errcode=1
+	fi
 
-debug "end ${_ROOT}/init"
+	jlb::debug "end ${path}/init"
+
+	jlb::funcEnd "${errcode}" ; return ${errcode}
+}
+
+JLB_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+# Root directory containing this repos' function file structure
+export JLB_ROOT
+
+#-> CHECK IF THE --debug FLAG HAS BEEN PASSED. IF SO, REMOVES IT AND SETS THE DEBUG VARIABLE TO true
+case $1 in
+	--debug)
+		shift
+		# Variable for confirming if debug mode is on
+		export JLB_DEBUG=true
+
+		# Variable for tracking the nesting depth of functions
+		export JLB_DEBUG_DEPTH=0
+
+		printf "DEBUG STATEMENTS ENABLED. THESE WILL GO TO STDERR SO AS NOT TO CONTAMINATE STRING RETURNS\n"
+	;;
+esac
+
+if [ -z "${JLB_TESTS+x}" ] ; then
+	# Variable for confirming if testing mode is on
+	export JLB_TESTS=false
+else
+	printf "Executing with JLB_TESTS=true\n"
+fi
+
+jlb::init "${JLB_ROOT}" || exit 1
diff --git a/functions/loader b/functions/loader
--- a/functions/loader
+++ b/functions/loader
@@ -1,5 +1,8 @@
 #! /bin/bash
 
+# The version of the function file in format "x.y.z".
+export JLB_LOADER_VERSION=1.0.0
+
 # Public: Primary function-file loader.
 #
 # Sources all files under the specified tree, to the specified depth, matching
@@ -11,11 +14,11 @@
 #
 # Examples
 #
-#   loader "./functions" "0" "*.sh"
+#   jlb::loader "./functions" "0" "*.sh"
 #
-# Always returns an exit code of 0
-function loader() {
-	funcStart
+# Returns a result of 0 unless it fails to source a file (i.e. syntax error in file)
+function jlb::loader() {
+	jlb::funcStart
 
 #-> PREP
 	local path			#-> VARIABLE CONTAINING STARTING PATH
@@ -23,6 +26,7 @@ function loader() {
 	local str			#-> VARIABLE CONTAINING FILE MATCHING GLOB
 	local depth			#-> VARIABLE FOR TRACKING CURRENT DEPTH
 	local depth_str		#-> VARIABLE FOR BUILDING DEPTH-BASED PATH TO SOURCE FROM
+	local status 		#-> VARIABLE FOR STORING THE EXIT CODE OF THE LAST OPERATION
 
 	path="${1}"			; shift
 	max_depth="${1}"	; shift
@@ -37,9 +41,9 @@ function loader() {
 		#-> INCREMENT MAX DEPTH BY ONE, SINCE IT COMES UP SHORT FOR OUR PURPOSES
 		((max_depth++))
 
-		debug "Maximum loader depth: ${max_depth} (max)"
+		jlb::debug "Maximum loader depth: ${max_depth} (max)"
 	else
-		debug "Maximum loader depth: ${max_depth}"
+		jlb::debug "Maximum loader depth: ${max_depth}"
 	fi
 
 	local depth=0
@@ -51,7 +55,7 @@ function loader() {
 		((depth++))
 
 		local target="${path}/${depth_str}${str}"
-		debug "Sourcing at depth ${depth} in directory ${path}/${depth_str}"
+		jlb::debug "Sourcing at depth ${depth} in directory ${path}/${depth_str}"
 
 		#-> LOOP FOR EACH FILE AT THE PATH EXPRESSED BY $SOURCE_PATH
 #		for f in `ls -v ${target}` ; do
@@ -62,14 +66,18 @@ function loader() {
 			if (( ${#files} )) ; then
 				# shellcheck disable=1090
 				source "$f"
-				errcode=$?
-				if [ ${errcode} -ne 0 ] ; then
-					debug "Failed to source $f"
+				status=$?
+				if [ ${status} -ne 0 ] ; then
+					errcode=1
+
+					jlb::debug "Failed to source $f"
+
+					jlb::funcEnd "${errcode}" ; return ${errcode}
 				else
-					debug "Sourced file: $f"
+					jlb::debug "Sourced file: $f"
 				fi
 			else
-				debug "empty (or does not exist, or is not a .sh file)"
+				jlb::debug "empty (or does not exist, or is not a .sh file)"
 			fi
 		done
 
@@ -77,6 +85,6 @@ function loader() {
 		depth_str="${depth_str}*/"
 	done
 
-	funcEnd
+	jlb::funcEnd
 	return 0
 }
